# Generated by Django 4.2.1 on 2023-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ffb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poinvid', models.CharField(max_length=50)),
                ('docudate', models.DateField(auto_now_add=True)),
                ('billid', models.CharField(max_length=50)),
                ('vendorcardid', models.CharField(max_length=50)),
                ('typecarid', models.CharField(max_length=50)),
                ('goodib', models.FloatField(default=0)),
                ('goodob', models.FloatField(default=0)),
                ('goodnet', models.FloatField(default=0)),
                ('price1', models.FloatField(default=0)),
                ('amnt1', models.FloatField(default=0)),
                ('price2', models.FloatField(default=0)),
                ('amnt2', models.FloatField(default=0)),
                ('vendorcode', models.CharField(max_length=20)),
                ('vendorname', models.CharField(max_length=100)),
                ('statusbill', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('impurity', models.CharField(max_length=5)),
                ('scaler', models.CharField(max_length=5)),
                ('docutype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labtank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('docudate', models.DateTimeField()),
                ('tankid', models.CharField(max_length=255, null=True)),
                ('level', models.FloatField(default=0)),
                ('tempid', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('ffa_top', models.FloatField(default=0)),
                ('moisture_top', models.FloatField(default=0)),
                ('dobi_top', models.FloatField(default=0)),
                ('ffa_low', models.FloatField(default=0)),
                ('moisture_low', models.FloatField(default=0)),
                ('dobi_low', models.FloatField(default=0)),
                ('user_rec', models.CharField(max_length=255, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('softDeletes', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tank_volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=5)),
                ('tank_high', models.FloatField(default=0)),
                ('tank_r', models.FloatField(default=0)),
                ('tank_v', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='temp_dense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.IntegerField(default=0)),
                ('cpo_dense', models.FloatField(default=0)),
            ],
        ),
    ]
