# Generated by Django 4.2.1 on 2023-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPlan',
            fields=[
                ('sopid', models.AutoField(primary_key=True, serialize=False)),
                ('SOPDate', models.DateField(null=True)),
                ('GoodID', models.IntegerField(null=True)),
                ('GoodName', models.CharField(max_length=128, null=True)),
                ('NumberCar', models.CharField(max_length=50, null=True)),
                ('DriverName', models.CharField(max_length=128, null=True)),
                ('CustID', models.IntegerField(null=True)),
                ('Recipient', models.CharField(max_length=128, null=True)),
                ('AmntLoad', models.IntegerField(null=True)),
                ('IBWei', models.IntegerField(null=True)),
                ('OBWei', models.IntegerField(null=True)),
                ('NetWei', models.IntegerField(null=True)),
                ('GoodPrice', models.FloatField(null=True)),
                ('GoodAmnt', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('Status', models.CharField(default='W', max_length=20, null=True)),
                ('ReceivedDate', models.DateTimeField(null=True)),
                ('Remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'SOPlan',
            },
        ),
        migrations.AlterField(
            model_name='ffb',
            name='statusbill',
            field=models.CharField(default='N', max_length=10, null=True),
        ),
    ]
